image: node:10.16.3

variables:
  NODE_ENV: ci
  POSTGRES_DB: signalboost_ci
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  paths:
    - node_modules/

test_unit:
  services:
    - name: postgres:latest
      alias: db
  script:
    - npm install
    - npx sequelize db:migrate --env ci
    - NODE_ENV=ci npx mocha ./test/unit  -name '*.spec.js' --recursive -r babel-register --reporter dot --exit