version: '3.4'

#  signald:
#    image: registry.0xacab.org/team-friendo/signalboost/signald
#    container_name: signalboost_signald
#    env_file: .env.dev
#    environment:
#      SIGNALD_VERBOSE_LOG: ${SIGNALD_VERBOSE_LOG:-0}
#    networks:
#      - default
#    expose:
#      - 1312
#    ports:
#      - 9010:9010
#    volumes:
#      - ./bin:/signalboost/bin
#      - ./signald/jmx:/var/lib/jmx
#      - signal_data:/var/lib/signald/data
#      - signal_sock:/var/run/signald/
#    restart: unless-stopped

x-signald-defaults: &signald-defaults
  image: registry.0xacab.org/team-friendo/signalboost/signald
  container_name: signalboost_signald
  env_file: .env.dev
  environment:
    SIGNALD_VERBOSE_LOG: ${SIGNALD_VERBOSE_LOG:-0}
  networks:
    - default
  expose:
    - 1312
  ports:
    - 9010:9010
  restart: unless-stopped

x-signald-default-volumes: &signald-default-volumes
  - ./bin:/signalboost/bin
  - ./signald/jmx:/var/lib/jmx
  - ./backups:/backups
  - signal_data:/var/lib/signald/data

# NOTE:
#
# we create a `localdev` network w/ a non-standard subnet mask to be able to use
# use docker from behdind a VPN, which is often necessary to auth w/ Signal.
# (see: https://github.com/docker/for-linux/issues/418#issuecomment-491323611)
#
# USAGE:
#
# for this to work you must first run the following (which is done automatically
# by `make _.setup`):
#
# ```bash
# docker network create localdev --subnet 10.0.1.0/24
# ```

networks:
  default:
    external:
      name: localdev

volumes:

  postgres_data:
  signal_sock:
  signal_data:
  prometheus_data:
  grafana_data:
  signal

services:

  db:
    image: postgres:12
    container_name: signalboost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always

  signald-0:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5000
    expose:
      - 5000
    volumes:
      - *signald-default-volumes
      - signal_sock_0:/var/run/signald/

  signald-1:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5001
    expose:
      - 5001
    volumes:
      - *signald-default-volumes
      - signal_sock_1:/var/run/signald/

  signald-2:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5002
    expose:
      - 5002
    volumes:
      - *signald-default-volumes
      - signal_sock_2:/var/run/signald/

  signald-3:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5003
    expose:
      - 5003
    volumes:
      - *signald-default-volumes
      - signal_sock_3:/var/run/signald/

  signald-4:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5004
    expose:
      - 5004
    volumes:
      - *signald-default-volumes
      - signal_sock_4:/var/run/signald/


  app:
    image: registry.0xacab.org/team-friendo/signalboost/signalboost:latest
    container_name: signalboost_app
    depends_on:
      - db
      - signald
    entrypoint: /signalboost/bin/entrypoint/app
    env_file: .env.dev
    environment:
      SIGNALBOOST_VERBOSE_LOG: ${SIGNALBOOST_VERBOSE_LOG:-0}
      PROJECT_ROOT: ${PWD}
      NODE_ENV: ${NODE_ENV:-development}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-EN}
      REREGISTER_ON_STARTUP: ${REREGISTER_ON_STARTUP:-0}
    expose:
      - 3000
    networks:
      - default
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - signal_data:/var/lib/signald/data
      - ./yarn.lock:/signalboost/yarn.lock
      - /var/run/docker.sock:/var/run/docker.sock
      - signal_sock_0:/var/run/signald/0
      - signal_sock_1:/var/run/signald/1
      - signal_sock_2:/var/run/signald/2
      - signal_sock_3:/var/run/signald/3
      - signal_sock_4:/var/run/signald/4
    restart: always

  ngrok:
    container_name: signalboost_ngrok
    ports:
      - 0.0.0.0:4040:4040
    networks:
      - default
    image: wernight/ngrok
    links:
      - app
    env_file: .env.dev
    environment:
      - NGROK_PORT=app:3000
    restart: always

  prometheus:
    image: prom/prometheus:v2.18.1
    ports:
      - 9090:9090
    user: root
    networks:
      - default
    volumes:
      - ./prometheus/prometheus_dev.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus_data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--log.level=debug'
    restart: always

  grafana:
    image: grafana/grafana:7.0.3
    depends_on:
      - prometheus
    ports:
      - 5000:5000
    networks:
      - default
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_HTTP_PORT=5000
    restart: always
