version: '3.4'

# see docker-compose.yml for defaults extended here

x-signald-overrides: &signald-overrides
  env_file: .env.dev

networks: # see [1]
  default:
    external:
      name: localdev

services:

  app:
    env_file: .env.dev

  signald_0:
    <<: *signald-overrides

  signald_1:
    <<: *signald-overrides

  signald_2:
    <<: *signald-overrides

  signald_3:
    <<: *signald-overrides

  signald_4:
    <<: *signald-overrides

  signald_5:
    <<: *signald-overrides

  signald_6:
    <<: *signald-overrides

  signald_7:
    <<: *signald-overrides

  signald_8:
    <<: *signald-overrides

  signald_9:
    <<: *signald-overrides

  ngrok:
    container_name: signalboost_ngrok
    ports:
      - 0.0.0.0:4040:4040
    networks:
      - default
    image: wernight/ngrok
    links:
      - app
    env_file: .env.dev
    environment:
      - NGROK_PORT=app:3000
    restart: always

# -----------------------------
# [1] NOTE:
#
# we create a `localdev` network w/ a non-standard subnet mask to be able to use
# use docker from behdind a VPN, which is often necessary to auth w/ Signal.
# (see: https://github.com/docker/for-linux/issues/418#issuecomment-491323611)
#
# USAGE:
#
# for this to work you must first run the following (which is done automatically
# by `make _.setup`):
#
# ```bash
# docker network create localdev --subnet 10.0.1.0/24
# ```
