version: '3'

networks:
  proxy-tier:

volumes:
  certs:
  html:
  postgres_data:
  nextcloud:
  vhost.d:

services:

  db:
    image: postgres
    container_name: signalboost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  orchestrator:
    image: signalboost
    container_name: signalboost_orchestrator
    depends_on:
      - db
    entrypoint: /signalboost/bin/entrypoint/orchestrator
    env_file: .env
    environment:
      PROJECT_ROOT: "$PWD"
      NODE_ENV: production
    networks:
      - proxy-tier
      - default
    ports:
      - 3000:3000
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./conf/supervisord:/signalboost/supervisord_conf
      - ./conf/dbus/org.asamk.Signal.conf:/etc/dbus-1/system.d/org.asamk.Signal.conf
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - ./logs:/signalboost/logs
      - ./signal_data:/root/.config/signal/data
      - ./yarn.lock:/signalboost/yarn.lock
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

