version: '3.4'

# TODO(aguestuser|2020-10-15)
# - this config file likely does not work with our current e2e test setup
# - but that's okay because we don't currently run e2e tests as part of our dev or CI flow!
# - we leave this sketch here as a courtesey to future devs who might impl. e2e tests and want
#   a place to start!

x-signald-overrides: &signald-overrides
  # TODO: probably want an .env.e2e file?
  env_file: .env.dev

services:

  app:
    env_file: .env.dev

  signald_0:
    <<: *signald-overrides
    volumes:
      - signald_sock_0:/var/run/signald/

  signald_1:
    <<: *signald-overrides
    volumes:
      - signald_sock_1:/var/run/signald/

  signald_2:
    <<: *signald-overrides
    volumes:
      - signald_sock_2:/var/run/signald/

  signald_3:
    <<: *signald-overrides
    volumes:
      - signald_sock_3:/var/run/signald/

  signald_4:
    <<: *signald-overrides
    volumes:
      - signald_sock_4:/var/run/signald/

  signald_5:
    <<: *signald-overrides
    volumes:
      - signald_sock_5:/var/run/signald/

  signald_6:
    <<: *signald-overrides
    volumes:
      - signald_sock_6:/var/run/signald/

  signald_7:
    <<: *signald-overrides
    volumes:
      - signald_sock_7:/var/run/signald/

  signald_8:
    <<: *signald-overrides
    volumes:
      - signald_sock_8:/var/run/signald/

  signald_9:
    <<: *signald-overrides
    volumes:
      - signald_sock_9:/var/run/signald/


  test_runner:
    image: signalboost
    container_name: signalboost_test_runner
    entrypoint: /signalboost/bin/entrypoint/test-e2e
    #TODO(aguestuser|2020-03-20): we should probably have an .env.test?
    environment:
      PROJECT_ROOT: "$PWD"
      NODE_ENV: "${NODE_ENV:-development}"
    depends_on:
      - ngrok
      - db
      - app
    env_file: .env.dev
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - signal_data:/var/lib/signald/data
      - signal_sock:/var/run/signald/
      - ./yarn.lock:/signalboost/yarn.lock
      - ./test:/signalboost/test
