version: '3.4'

networks:
  proxy-tier:

volumes:
  certs:
  html:
  nextcloud:
  postgres_data:
  signal_sock:
  signal_data:

x-logging: &loki-logging
  options:
    loki-url: ${LOKI_URL}
  driver: loki

services:

  db:
    image: postgres:12
    container_name: signalboost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    # as per https://github.com/docker-library/postgres/issues/692
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    logging: *loki-logging
    restart: unless-stopped

  signald:
    image: signald
    container_name: signalboost_signald
    environment:
      VIRTUAL_HOST: ${SIGNALD_HOST_URL}
      VIRTUAL_PORT: ${SIGNALD_PORT}
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL}
      SIGNALBOOST_HOST_IP: ${SIGNALBOOST_HOST_IP}
      SIGNALD_VERBOSE_LOG: ${SIGNALD_VERBOSE_LOG:-0}
    ports:
      - 9010:9010
    networks:
      - default
    volumes:
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - signal_data:/var/lib/signald/data
      - signal_sock:/var/run/signald/
      - ./backups:/backups
    logging: *loki-logging
    restart: unless-stopped

  app:
    image: signalboost
    container_name: signalboost_app
    depends_on:
      - db
      - signald
    entrypoint: /signalboost/bin/entrypoint/app
    env_file: .env
    environment:
      VIRTUAL_HOST: ${SIGNALBOOST_HOST_URL}
      VIRTUAL_PORT: ${SIGNALBOOST_PORT}
      LETSENCRYPT_HOST: ${SIGNALBOOST_HOST_URL}
      SIGNALBOOST_VERBOSE_LOG: ${SIGNALBOOST_VERBOSE_LOG:-1}
      PROJECT_ROOT: $PWD
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-EN}
      NODE_ENV: production
    expose:
      - ${SIGNALBOOST_PORT}
    networks:
      - proxy-tier
      - default
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - signal_data:/var/lib/signald/data
      - signal_sock:/var/run/signald/
      - ./yarn.lock:/signalboost/yarn.lock
    logging: *loki-logging
    restart: unless-stopped

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: signalboost_proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    logging: *loki-logging
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: signalboost_letsencrypt
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    logging: *loki-logging
    depends_on:
      - proxy
