version: '3'

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  certs:
  html:

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    user: root
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus_prod.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus_data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--log.level=debug'
    env_file: .env.metrics
    environment:
      - VIRTUAL_HOST=${PROM_HOST}
      - VIRTUAL_PORT=${PROM_PORT}
      - LETSENCRYPT_HOST=${PROM_HOST}
    restart: unless-stopped

  loki:
    image: grafana/loki:1.5.0
    user: root
    expose:
      - 3100
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/data/loki
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    env_file: .env.metrics
    environment:
      - VIRTUAL_HOST=${LOKI_HOST}
      - VIRTUAL_PORT=${LOKI_PORT}
      - LETSENCRYPT_HOST=${LOKI_HOST}
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:7.0.3
    depends_on:
      - prometheus
    expose:
      - 5000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    env_file: .env.metrics
    environment:
      - VIRTUAL_HOST=${METRICS_HOST}
      - VIRTUAL_PORT=${METRICS_PORT}
      - LETSENCRYPT_HOST=${METRICS_HOST}
      - GF_SERVER_HTTP_PORT=5000
    restart: unless-stopped

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: signalboost_proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: signalboost_letsencrypt
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
