version: '3.4'

#
# ANCHORS
#

x-loki-logging: &loki-logging
  options:
    loki-url: ${LOKI_URL}
  driver: loki

x-signald-default-volumes: &signald-default-volumes
  - ./bin:/signalboost/bin
  - ./signald/jmx:/var/lib/jmx
  - ./backups:/backups
  - signal_data:/var/lib/signald/data
  #- signal_sock:/var/run/signald/

x-signald-defaults: &signald-defaults
  image: registry.0xacab.org/team-friendo/signalboost/signald:latest
  container_name: signalboost_signald
  env_file: .env
  environment:
    VIRTUAL_HOST: ${SIGNALD_HOST_URL}
    VIRTUAL_PORT: 1312
    METRICS_PORT: 1312
    LETSENCRYPT_HOST: ${SIGNALD_HOST_URL}
    SIGNALBOOST_HOST_IP: ${SIGNALBOOST_HOST_IP}
    SIGNALD_VERBOSE_LOG: ${SIGNALD_VERBOSE_LOG:-0}
    DD_AGENT_HOST: datadog-agent
    DD_TRACE_AGENT_PORT: 8126
  expose:
    - 500
  ports:
    - 9010:9010
  networks:
    - default
    - proxy-tier
  logging: *loki-logging
  restart: unless-stopped


#
# NAMED RESOURCES
#

networks:
  proxy-tier:

volumes:
  certs:
  html:
  nextcloud:
  postgres_data:
  signal_sock:
  signal_data:

#
# SERVICES
#

services:

  db:
    image: postgres:12
    container_name: signalboost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    # as per https://github.com/docker-library/postgres/issues/692
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    logging: *loki-logging
    restart: always

  app:
    image: registry.0xacab.org/team-friendo/signalboost/signalboost:latest
    container_name: signalboost_app
    depends_on:
      - db
      - signald
    entrypoint: /signalboost/bin/entrypoint/app
    env_file: .env
    environment:
      VIRTUAL_HOST: ${SIGNALBOOST_HOST_URL}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${SIGNALBOOST_HOST_URL}
      SIGNALBOOST_VERBOSE_LOG: ${SIGNALBOOST_VERBOSE_LOG:-1}
      REREGISTER_ON_STARTUP: ${REREGISTER_ON_STARTUP:-0}
      PROJECT_ROOT: $PWD
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-EN}
      NODE_ENV: production
    expose:
      - 3000
    networks:
      - proxy-tier
      - default
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - ./yarn.lock:/signalboost/yarn.lock
      - signal_data:/var/lib/signald/data
      - signal_sock_0:/var/run/signald/0
      - signal_sock_1:/var/run/signald/1
      - signal_sock_1:/var/run/signald/1
    logging: *loki-logging
    restart: always

  signald-0:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5000
    expose:
      - 5000
    volumes:
      <<: *signald-default-volumes
      - signal_sock_1:/var/run/signald/

  signald-1:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5001
    expose:
      - 5001
    volumes:
      <<: *signald-default-volumes
      - signal_sock_1:/var/run/signald/

  signald-2:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5002
    expose:
      - 5002
    volumes:
      <<: *signald-default-volumes
      - signal_sock_2:/var/run/signald/

  signald-3:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5003
    expose:
      - 5003
    volumes:
      <<: *signald-default-volumes
      - signal_sock_3:/var/run/signald/

  signald-4:
    <<: *signald-defaults
    environment:
      METRICS_PORT: 5004
    expose:
      - 5004
    volumes:
      <<: *signald-default-volumes
      - signal_sock_4:/var/run/signald/

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: signalboost_proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    logging: *loki-logging
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: signalboost_letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    logging: *loki-logging
    depends_on:
      - proxy
