version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  orchestrator:
      build:
        context: .
        dockerfile: docker/orchestrator.dockerfile
      env_file: .env
      environment:
        NODE_ENV: "${NODE_ENV:-production}"
      stdin_open: true
      tty: true
      ports:
        - 3000:3000
      volumes:
        - ./app:/app
        - ./package.json:/package.json
        - ./node_modules:/node_modules
        - ./yarn.lock:/yarn.lock
        - ./.sequelizerc:/.sequelizerc

  # dispatcher0:
  #   build:
  #     context: .
  #     dockerfile: docker/dispatcher.dockerfile
  #   env_file: .env
  #   environment:
  #     NODE_ENV: "${NODE_ENV:-production}"
  #     CHANNEL_PHONE_NUMBER: "+15129910157"
  #   volumes:
  #     - ./app:/app
  #     - ./package.json:/package.json
  #     - ./node_modules:/node_modules
  #     - ./yarn.lock:/yarn.lock
  #     - ./.sequelizerc:/.sequelizerc

# TODO: share signal conf dir across services with something like...
# volumes:
#   - ./tmp/signalconf:/root/.conf/signal/
