version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  dispatcher:
    build:
      context: .
      dockerfile: dispatcher.dockerfile
    env_file: .env
    environment:
      NODE_ENV: "${NODE_ENV:-production}"
      CHANNEL_PHONE_NUMBER: "+15122707190"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
      - ./package.json:/package.json
      - ./node_modules:/node_modules
      - ./yarn.lock:/yarn.lock
      - ./.sequelizerc:/.sequelizerc

# TODO: share signal conf dir across services with something like...
# volumes:
#   signal_conf: ./tmp/signalconf:/root/.conf/signal/
