version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  dispatcher0:
    build:
      context: .
      dockerfile: dispatcher.dockerfile
    env_file: .env
    environment:
      NODE_ENV: "${NODE_ENV:-production}"
      CHANNEL_PHONE_NUMBER: "+15129910157"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
      - ./package.json:/package.json
      - ./node_modules:/node_modules
      - ./yarn.lock:/yarn.lock
      - ./.sequelizerc:/.sequelizerc
  dispatcher1:
    build:
      context: .
      dockerfile: dispatcher.dockerfile
    env_file: .env
    environment:
      NODE_ENV: "${NODE_ENV:-production}"
      CHANNEL_PHONE_NUMBER: "+15122707190"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
      - ./package.json:/package.json
      - ./node_modules:/node_modules
      - ./yarn.lock:/yarn.lock
      - ./.sequelizerc:/.sequelizerc

# TODO: share signal conf dir across services with something like...
# volumes:
#   - ./tmp/signalconf:/root/.conf/signal/
