---
- name: Create backup and copy it to remote storage
  become: true
  hosts: signalboost

  vars:
    homedir: /srv/signalboost
    env_file: "files/.env"
    secrets_method: copy

  tasks:

  - name: Deploy environment file using blackbox
    command: ./bin/blackbox/postdeploy
    args:
      chdir: "{{ homedir }}"
    tags: secrets
    when: secrets_method == "blackbox"

  - name: Deploy environment file by copying local file
    copy:
      src: "{{ env_file }}"
      dest: "{{ homedir }}/.env"
    tags: secrets
    when: secrets_method == "copy"

  - name: Run backup script
    command: ./bin/backup
    args:
      chdir: "{{ homedir }}"
