---
- name: Configure Signalboost
  become: true
  hosts: signalboost

  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
    secrets_method: copy

  # install docker dependencies
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:

    ########
    # KEYS #
    ########

    - name: Load Deploy Key(s)
      copy:
        src: files/deploy_keys/
        dest: /keys/
      tags: keys
      when: secrets_method == 'blackbox'

    - name: Import GPG deploy key to keystore
      command: gpg --import signalboost_gpg_privkey.asc
      args:
        chdir: /keys
      tags: keys
      when: secrets_method == 'blackbox'

    ################
    # DOCKER IMAGE #
    ################

    - name: Load base dockerfiles
      copy:
        src: files/docker/
        dest: /srv/signalboost/docker/
      tags: docker

    - name: Build signalboost container
      command: docker build -f /srv/signalboost/docker/signalboost.dockerfile -t signalboost:latest /srv/signalboost
      register: build_output
      tags: docker

    - name: Build signald container
      command: docker build -f /srv/signalboost/docker/signald.dockerfile -t signald:latest /srv/signalboost
      register: build_output
      tags: docker
