---
- name: Perform Advanced Hardening
  become: true
  hosts: "{{ sb_host | default('signalboost') }}"

  tasks:
    - name: Run dev-sec os-hardening role
      import_role:
        name: dev-sec.os-hardening
