scrape_configs:

  - job_name: 'signalboost-registrar'
    scrape_interval: 5s    
    static_configs:
    - targets: ['app:3000']
    metrics_path: '/metrics'

  - job_name: 'signalboost-dispatcher'
    scrape_interval: 5s    
    static_configs:
    - targets: ['app:3030']
    metrics_path: '/metrics'
    
  
  
