---
- name: Deploy Splash
  become: true
  hosts: splash

  environment:
    NODE_ENV: production

  vars:
    rootdir: /srv
    homedir: /srv/splash
    env_file: "files/.env"
    secrets_method: copy

  tasks:

  #########
  # CLONE #
  #########

  - name: Pull signalboost repository from 0xacab
    git:
      repo: https://0xacab.org/team-friendo/signalboost
      dest: "{{ rootdir }}"
      force: true
      version: "{{ branch | default('master') }}"
    tags: clone

  - name: Deploy environment file using blackbox
    command: ./bin/blackbox/postdeploy
    args:
      chdir: "{{ homedir }}"
    tags: clone
    when: secrets_method == "blackbox"

  - name: Deploy environment file by copying local file
    copy:
      src: "{{ env_file }}"
      dest: "{{ homedir }}/.env"
    tags: clone
    when: secrets_method == "copy"

  ########################
  # UPDATE DOCKER IMAGES #
  ########################

  - name: Pull latest splash container
    command: "docker-compose pull splash"
    args:
      chdir: "{{ homedir }}"
    tags: prepare, docker

    # to ensure ACMEv2 compatibility
    # (as per, e.g.: https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/598)
  - name: Pull latest version of letsencrypt companion
    command: "docker-compose pull letsencrypt"
    args:
      chdir: "{{ homedir }}"
    tags: prepare, docker


  ####################
  # UPDATE NODE DEPS #
  ####################

  - name: Install node packages
    command: "docker-compose run --entrypoint '/splash/bin/entrypoint/install' splash"
    args:
      chdir: "{{ homedir }}"
    tags: prepare

  ########
  # STOP #
  ########

  - name: Stop app
    command: "docker-compose down"
    args:
      chdir: "{{ homedir }}"
    tags: stop

  #########
  # START #
  #########

  - name: Start app
    command: "docker-compose up -d"
    args:
      chdir: "{{ homedir }}"
    register: docker_up_result
    tags: start

  # - debug:
  #     var: docker_up_result
