version: '3'

services:

  splash:
    image: registry.0xacab.org/team-friendo/signalboost/splash
    container_name: signalboost_splash
    entrypoint: "gatsby develop -H 0.0.0.0"
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    ports:
      - 8000:8000
    networks:
      - default
    volumes:
      - ./:/splash
    restart: always
